### PR TITLE
WIP: Add AgainstInvalidEnumArgument & AgainstInvalidEnumArgumentProperty

### PR DESCRIPTION
**Pull request by SeanKilleen**
connects to #108.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@adamralph added signatures for review / confirmation. Let me know if those make sense.

Also, where the heck am I adding this? I saw the acceptance test was off of .NET 3.5 but it doesn't look at first glance like those files are linked. Will I eventually be copying the code to various places once it's passed acceptance testing?

**Comment by SeanKilleen** [comment]
I guess breaking the build a few times is a good way to get started. :smile:

**Comment by adamralph** [comment]
@SeanKilleen the signatures I had in mind are those I wrote in https://github.com/liteguard/liteguard/issues/108#issuecomment-116256648 - what's your opinion on them?

BTW - [ValidatedNotNull] isn't required since we have the struct constraint.

The multi-targetting is awkward. Ultimately you need to copy the changes into all the different versions of Guard.cs in all the projects :unamused:. You can get everything working on the .net 35 project first though.

**Comment by SeanKilleen** [comment]
@adamralph sorry, that feedback on `ValidatedNotNull` is exactly what I meant I was looking for. Thanks!

**Comment by adamralph** [comment]
BTW - I've just pushed a change to master which means there are now only two versions of Guard.cs.

**Comment by SeanKilleen** [comment]
I'll pull it in -- thanks!

**Comment by adamralph** [comment]
Closing, since we agreed to withdraw #108.

**Pull request closed without merging**
